# Global build settings
[build]
   base    = ""
   publish = "dist/"
   command = "sed -i s/API_URL_PLACEHOLDER/$API_URL/g netlify.toml && NODE_PATH=src REACT_APP_API_URL='' npm run build"

# Redirects
[[redirects]]
  from = "/api/v1/*"
  to = "API_URL_PLACEHOLDER/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200